version: 2.1
with_db: &with_db
  docker:
    - image: circleci/node:10-browsers
      environment:
        JOBS: 2
        PG_USER: acbe
        PG_NAME: swag_test
        PG_HOST: localhost
        PG_PORT: 5432
        NODE_ENV: ci
        SECRET: $SECRET
        GOOGLE_REFRESH_TOKEN: $GOOGLE_REFRESH_TOKEN
        GOOGLE_KEY: $GOOGLE_KEY
        GOOGLE_SECRET: $GOOGLE_SECRET
        GOOGLE_REDIRECT: $GOOGLE_REDIRECT
    - image: circleci/postgres:10.10
      environment:
        POSTGRES_USER: acbe
        POSTGRES_DB: swag_test
  working_directory: ~/ember-circleci
without_db: &without_db
  docker:
    - image: circleci/node:14-browsers
      environment:
        JOBS: 1
        NODE_ENV: ci
    - image: circleci/postgres:10.10
  working_directory: ~/ember-circleci
orbs:
  cypress: cypress-io/cypress@1
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  install_dependencies:
    <<: *without_db
    steps:
      - checkout
      - run:
          name: Update yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Project dependencies
          command: yarn  --frozen-lockfile
      - run:
          name: Install API dependencies
          command: yarn  --frozen-lockfile --cwd ./server
      - run:
          name: Install Ember dependencies
          command: yarn  --frozen-lockfile --cwd ./frontend
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ~/.cache/Cypress
            - node_modules
            - frontend/node_modules
            - server/node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - ember-circleci
            - .cache/yarn
            - .cache/Cypress
  build:
    <<: *without_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Ember
          command: cd frontend && $(yarn bin)/ember build; cd ../
      - persist_to_workspace:
          root: ~/
          paths:
            - ember-circleci/frontend/dist
  lint_server:
    <<: *without_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint API
          command: yarn --cwd ./server lint:js
  test_server:
    <<: *with_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: migrate db
          command: cd server && $(yarn bin)/knex migrate:latest; cd ../
      - run:
          name: seed db
          command: cd server && $(yarn bin)/knex seed:run; cd ../
      - run:
          name: Test API
          command: yarn --cwd ./server test
      - store_test_results:
          path: server/coverage
  lint_frontend_js:
    <<: *without_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Ember JS
          command: yarn --cwd ./frontend lint:js
  lint_frontend_hbs:
    <<: *without_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Lint Ember hbs
          command: yarn --cwd ./frontend lint:hbs
  integration_test:
    <<: *with_db
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: migrate db
          command: cd server && $(yarn bin)/knex migrate:latest; cd ../
      - run:
          name: seed db
          command: cd server && $(yarn bin)/knex seed:run; cd ../
      - run:
          name: Start API
          command: node server/index.js
          background: true
      - run:
          name: Start Ember
          command: yarn --cwd ./frontend ci:start
          background: true
      - run:
          name: Run Cypress
          command: $(yarn bin)/cypress run
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint_server:
          requires:
            - install_dependencies
      - test_server:
          requires:
            - build
      - lint_frontend_hbs:
          requires:
            - install_dependencies
      - lint_frontend_js:
          requires:
            - install_dependencies
      - integration_test:
          requires:
            - build

